CD /d "%~dp0"
rem doc目录下查找：-fr|-it|-ja|-pl|-ru
DEL /q/f vim80\doc\evim-fr.1
DEL /q/f vim80\doc\evim-fr.UTF-8.1
DEL /q/f vim80\doc\evim-it.1
DEL /q/f vim80\doc\evim-it.UTF-8.1
DEL /q/f vim80\doc\evim-ja.UTF-8.1
DEL /q/f vim80\doc\evim-pl.1
DEL /q/f vim80\doc\evim-pl.UTF-8.1
DEL /q/f vim80\doc\evim-ru.1
DEL /q/f vim80\doc\evim-ru.UTF-8.1
DEL /q/f vim80\doc\vimdiff-fr.1
DEL /q/f vim80\doc\vimdiff-fr.UTF-8.1
DEL /q/f vim80\doc\vimdiff-it.1
DEL /q/f vim80\doc\vimdiff-it.UTF-8.1
DEL /q/f vim80\doc\vimdiff-ja.UTF-8.1
DEL /q/f vim80\doc\vimdiff-pl.1
DEL /q/f vim80\doc\vimdiff-pl.UTF-8.1
DEL /q/f vim80\doc\vimdiff-ru.1
DEL /q/f vim80\doc\vimdiff-ru.UTF-8.1
DEL /q/f vim80\doc\vim-fr.1
DEL /q/f vim80\doc\vim-fr.UTF-8.1
DEL /q/f vim80\doc\vim-it.1
DEL /q/f vim80\doc\vim-it.UTF-8.1
DEL /q/f vim80\doc\vim-ja.UTF-8.1
DEL /q/f vim80\doc\vim-pl.1
DEL /q/f vim80\doc\vim-pl.UTF-8.1
DEL /q/f vim80\doc\vim-ru.1
DEL /q/f vim80\doc\vim-ru.UTF-8.1
DEL /q/f vim80\doc\vimtutor-fr.1
DEL /q/f vim80\doc\vimtutor-fr.UTF-8.1
DEL /q/f vim80\doc\vimtutor-it.1
DEL /q/f vim80\doc\vimtutor-it.UTF-8.1
DEL /q/f vim80\doc\vimtutor-ja.UTF-8.1
DEL /q/f vim80\doc\vimtutor-pl.1
DEL /q/f vim80\doc\vimtutor-pl.UTF-8.1
DEL /q/f vim80\doc\vimtutor-ru.1
DEL /q/f vim80\doc\vimtutor-ru.UTF-8.1
DEL /q/f vim80\doc\xxd-fr.1
DEL /q/f vim80\doc\xxd-fr.UTF-8.1
DEL /q/f vim80\doc\xxd-it.1
DEL /q/f vim80\doc\xxd-it.UTF-8.1
DEL /q/f vim80\doc\xxd-ja.UTF-8.1
DEL /q/f vim80\doc\xxd-pl.1
DEL /q/f vim80\doc\xxd-pl.UTF-8.1
DEL /q/f vim80\doc\xxd-ru.1
DEL /q/f vim80\doc\xxd-ru.UTF-8.1

rem 在tutor目录查找：.bar|.bg|.ca|.cs|.de|.el|.eo|.es|.fr|.hr|.hu|.it|.ja|.ko|.nb|.nl|.no|.pl|.ru|.sk|.sr|.sv|.tr|.uk|.vi
DEL /q/f vim80\tutor\README.el.txt
DEL /q/f vim80\tutor\README.el.cp737.txt
DEL /q/f vim80\tutor\tutor.bar
DEL /q/f vim80\tutor\tutor.ca
DEL /q/f vim80\tutor\tutor.cs
DEL /q/f vim80\tutor\tutor.de
DEL /q/f vim80\tutor\tutor.el
DEL /q/f vim80\tutor\tutor.eo
DEL /q/f vim80\tutor\tutor.es
DEL /q/f vim80\tutor\tutor.fr
DEL /q/f vim80\tutor\tutor.hr
DEL /q/f vim80\tutor\tutor.hu
DEL /q/f vim80\tutor\tutor.it
DEL /q/f vim80\tutor\tutor.nb
DEL /q/f vim80\tutor\tutor.nl
DEL /q/f vim80\tutor\tutor.no
DEL /q/f vim80\tutor\tutor.pl
DEL /q/f vim80\tutor\tutor.ru
DEL /q/f vim80\tutor\tutor.sk
DEL /q/f vim80\tutor\tutor.sv
DEL /q/f vim80\tutor\tutor.bar.utf-8
DEL /q/f vim80\tutor\tutor.bg.utf-8
DEL /q/f vim80\tutor\tutor.ca.utf-8
DEL /q/f vim80\tutor\tutor.cs.cp1250
DEL /q/f vim80\tutor\tutor.cs.utf-8
DEL /q/f vim80\tutor\tutor.de.utf-8
DEL /q/f vim80\tutor\tutor.el.cp737
DEL /q/f vim80\tutor\tutor.el.utf-8
DEL /q/f vim80\tutor\tutor.eo.utf-8
DEL /q/f vim80\tutor\tutor.es.utf-8
DEL /q/f vim80\tutor\tutor.fr.utf-8
DEL /q/f vim80\tutor\tutor.hr.cp1250
DEL /q/f vim80\tutor\tutor.hr.utf-8
DEL /q/f vim80\tutor\tutor.hu.cp1250
DEL /q/f vim80\tutor\tutor.hu.utf-8
DEL /q/f vim80\tutor\tutor.it.utf-8
DEL /q/f vim80\tutor\tutor.ja.euc
DEL /q/f vim80\tutor\tutor.ja.sjis
DEL /q/f vim80\tutor\tutor.ja.utf-8
DEL /q/f vim80\tutor\tutor.ko.euc
DEL /q/f vim80\tutor\tutor.ko.utf-8
DEL /q/f vim80\tutor\tutor.nb.utf-8
DEL /q/f vim80\tutor\tutor.nl.utf-8
DEL /q/f vim80\tutor\tutor.no.utf-8
DEL /q/f vim80\tutor\tutor.pl.cp1250
DEL /q/f vim80\tutor\tutor.pl.utf-8
DEL /q/f vim80\tutor\tutor.ru.cp1251
DEL /q/f vim80\tutor\tutor.ru.utf-8
DEL /q/f vim80\tutor\tutor.sk.cp1250
DEL /q/f vim80\tutor\tutor.sk.utf-8
DEL /q/f vim80\tutor\tutor.sr.cp1250
DEL /q/f vim80\tutor\tutor.sr.utf-8
DEL /q/f vim80\tutor\tutor.sv.utf-8
DEL /q/f vim80\tutor\tutor.tr.iso9
DEL /q/f vim80\tutor\tutor.tr.utf-8
DEL /q/f vim80\tutor\tutor.uk.utf-8
DEL /q/f vim80\tutor\tutor.vi.utf-8

rem lang目录下清理：
RD /s/q vim80\lang\af\
RD /s/q vim80\lang\ca\
RD /s/q vim80\lang\cs\
RD /s/q vim80\lang\cs.cp1250\
RD /s/q vim80\lang\de\
RD /s/q vim80\lang\eo\
RD /s/q vim80\lang\es\
RD /s/q vim80\lang\fi\
RD /s/q vim80\lang\fr\
RD /s/q vim80\lang\ga\
RD /s/q vim80\lang\it\
RD /s/q vim80\lang\ja\
RD /s/q vim80\lang\ja.euc-jp\
RD /s/q vim80\lang\ja.sjis\
RD /s/q vim80\lang\ko\
RD /s/q vim80\lang\ko.UTF-8\
RD /s/q vim80\lang\nb\
RD /s/q vim80\lang\nl\
RD /s/q vim80\lang\no\
RD /s/q vim80\lang\pl\
RD /s/q vim80\lang\pl.cp1250\
RD /s/q vim80\lang\pl.UTF-8\
RD /s/q vim80\lang\pt_BR\
RD /s/q vim80\lang\ru\
RD /s/q vim80\lang\ru.cp1251\
RD /s/q vim80\lang\sk\
RD /s/q vim80\lang\sk.cp1250\
RD /s/q vim80\lang\sv\
RD /s/q vim80\lang\uk\
RD /s/q vim80\lang\uk.cp1251\
RD /s/q vim80\lang\vi\
DEL /q/f vim80\lang\menu_af.latin1.vim
DEL /q/f vim80\lang\menu_af.utf-8.vim
DEL /q/f vim80\lang\menu_af_af.latin1.vim
DEL /q/f vim80\lang\menu_af_af.utf-8.vim
DEL /q/f vim80\lang\menu_ca.latin1.vim
DEL /q/f vim80\lang\menu_ca.utf-8.vim
DEL /q/f vim80\lang\menu_ca_es.latin1.vim
DEL /q/f vim80\lang\menu_ca_es.utf-8.vim
DEL /q/f vim80\lang\menu_cs.cp1250.vim
DEL /q/f vim80\lang\menu_cs.latin1.vim
DEL /q/f vim80\lang\menu_cs_cz.cp1250.vim
DEL /q/f vim80\lang\menu_cs_cz.iso_8859-2.vim
DEL /q/f vim80\lang\menu_cs_cz.latin1.vim
DEL /q/f vim80\lang\menu_cs_cz.utf-8.vim
DEL /q/f vim80\lang\menu_czech_czech_republic.1250.vim
DEL /q/f vim80\lang\menu_czech_czech_republic.1252.vim
DEL /q/f vim80\lang\menu_czech_czech_republic.ascii.vim
DEL /q/f vim80\lang\menu_de.latin1.vim
DEL /q/f vim80\lang\menu_de.utf-8.vim
DEL /q/f vim80\lang\menu_de_de.latin1.vim
DEL /q/f vim80\lang\menu_de_de.utf-8.vim
DEL /q/f vim80\lang\menu_eo.utf-8.vim
DEL /q/f vim80\lang\menu_eo_eo.utf-8.vim
DEL /q/f vim80\lang\menu_eo_xx.utf-8.vim
DEL /q/f vim80\lang\menu_es.latin1.vim
DEL /q/f vim80\lang\menu_es.utf-8.vim
DEL /q/f vim80\lang\menu_es_es.latin1.vim
DEL /q/f vim80\lang\menu_es_es.utf-8.vim
DEL /q/f vim80\lang\menu_fi.latin1.vim
DEL /q/f vim80\lang\menu_fi.utf-8.vim
DEL /q/f vim80\lang\menu_fi_fi.latin1.vim
DEL /q/f vim80\lang\menu_fi_fi.utf-8.vim
DEL /q/f vim80\lang\menu_finnish_finland.1252.vim
DEL /q/f vim80\lang\menu_fr.latin1.vim
DEL /q/f vim80\lang\menu_fr.utf-8.vim
DEL /q/f vim80\lang\menu_fr_fr.latin1.vim
DEL /q/f vim80\lang\menu_fr_fr.utf-8.vim
DEL /q/f vim80\lang\menu_french_france.1252.vim
DEL /q/f vim80\lang\menu_german_germany.1252.vim
DEL /q/f vim80\lang\menu_hu.iso_8859-2.vim
DEL /q/f vim80\lang\menu_hu.utf-8.vim
DEL /q/f vim80\lang\menu_hu_hu.iso_8859-2.vim
DEL /q/f vim80\lang\menu_hu_hu.utf-8.vim
DEL /q/f vim80\lang\menu_it.latin1.vim
DEL /q/f vim80\lang\menu_it.utf-8.vim
DEL /q/f vim80\lang\menu_it_it.latin1.vim
DEL /q/f vim80\lang\menu_it_it.utf-8.vim
DEL /q/f vim80\lang\menu_italian_italy.1252.vim
DEL /q/f vim80\lang\menu_ja.cp932.vim
DEL /q/f vim80\lang\menu_ja.eucjp.vim
DEL /q/f vim80\lang\menu_ja.euc-jp.vim
DEL /q/f vim80\lang\menu_ja.ujis.vim
DEL /q/f vim80\lang\menu_ja.utf-8.vim
DEL /q/f vim80\lang\menu_ja_jp.cp932.vim
DEL /q/f vim80\lang\menu_ja_jp.eucjp.vim
DEL /q/f vim80\lang\menu_ja_jp.euc-jp.vim
DEL /q/f vim80\lang\menu_ja_jp.ujis.vim
DEL /q/f vim80\lang\menu_ja_jp.utf-8.vim
DEL /q/f vim80\lang\menu_japanese_japan.932.vim
DEL /q/f vim80\lang\menu_ko.utf-8.vim
DEL /q/f vim80\lang\menu_ko_kr.vim
DEL /q/f vim80\lang\menu_ko_kr.euckr.vim
DEL /q/f vim80\lang\menu_ko_kr.utf-8.vim
DEL /q/f vim80\lang\menu_nl.latin1.vim
DEL /q/f vim80\lang\menu_nl.utf-8.vim
DEL /q/f vim80\lang\menu_nl_nl.latin1.vim
DEL /q/f vim80\lang\menu_nl_nl.utf-8.vim
DEL /q/f vim80\lang\menu_no.latin1.vim
DEL /q/f vim80\lang\menu_no.utf-8.vim
DEL /q/f vim80\lang\menu_no_no.latin1.vim
DEL /q/f vim80\lang\menu_no_no.utf-8.vim
DEL /q/f vim80\lang\menu_pl.cp1250.vim
DEL /q/f vim80\lang\menu_pl_pl.cp1250.vim
DEL /q/f vim80\lang\menu_pl_pl.iso_8859-2.vim
DEL /q/f vim80\lang\menu_pl_pl.utf-8.vim
DEL /q/f vim80\lang\menu_polish_poland.1250.vim
DEL /q/f vim80\lang\menu_pt_br.vim
DEL /q/f vim80\lang\menu_pt_br.latin1.vim
DEL /q/f vim80\lang\menu_pt_br.utf-8.vim
DEL /q/f vim80\lang\menu_pt_pt.vim
DEL /q/f vim80\lang\menu_pt_pt.latin1.vim
DEL /q/f vim80\lang\menu_pt_pt.utf-8.vim
DEL /q/f vim80\lang\menu_ru.utf-8.vim
DEL /q/f vim80\lang\menu_ru_ru.vim
DEL /q/f vim80\lang\menu_ru_ru.koi8-r.vim
DEL /q/f vim80\lang\menu_ru_ru.utf-8.vim
DEL /q/f vim80\lang\menu_sk.cp1250.vim
DEL /q/f vim80\lang\menu_sk_sk.vim
DEL /q/f vim80\lang\menu_sk_sk.1250.vim
DEL /q/f vim80\lang\menu_sk_sk.cp1250.vim
DEL /q/f vim80\lang\menu_sk_sk.iso_8859-2.vim
DEL /q/f vim80\lang\menu_sl_si.cp1250.vim
DEL /q/f vim80\lang\menu_sl_si.latin2.vim
DEL /q/f vim80\lang\menu_sl_si.utf-8.vim
DEL /q/f vim80\lang\menu_slovak_slovak_republic.1250.vim
DEL /q/f vim80\lang\menu_spanish_spain.850.vim
DEL /q/f vim80\lang\menu_sr.utf-8.vim
DEL /q/f vim80\lang\menu_sr_rs.ascii.vim
DEL /q/f vim80\lang\menu_sr_rs.iso_8859-2.vim
DEL /q/f vim80\lang\menu_sr_rs.iso_8859-5.vim
DEL /q/f vim80\lang\menu_sr_rs.utf-8.vim
DEL /q/f vim80\lang\menu_sr_yu.ascii.vim
DEL /q/f vim80\lang\menu_sr_yu.iso_8859-2.vim
DEL /q/f vim80\lang\menu_sr_yu.iso_8859-5.vim
DEL /q/f vim80\lang\menu_sr_yu.utf-8.vim
DEL /q/f vim80\lang\menu_sv.latin1.vim
DEL /q/f vim80\lang\menu_sv.utf-8.vim
DEL /q/f vim80\lang\menu_sv_se.latin1.vim
DEL /q/f vim80\lang\menu_sv_se.utf-8.vim
DEL /q/f vim80\lang\menu_uk_ua.cp1251.vim
DEL /q/f vim80\lang\menu_uk_ua.koi8-u.vim
DEL /q/f vim80\lang\menu_vi_vn.vim

rem spell目录下清理：
RD /s/q vim80\spell\af\
RD /s/q vim80\spell\am\
RD /s/q vim80\spell\bg\
RD /s/q vim80\spell\br\
RD /s/q vim80\spell\ca\
RD /s/q vim80\spell\cs\
RD /s/q vim80\spell\cy\
RD /s/q vim80\spell\da\
RD /s/q vim80\spell\de\
RD /s/q vim80\spell\el\
RD /s/q vim80\spell\eo\
RD /s/q vim80\spell\es\
RD /s/q vim80\spell\fo\
RD /s/q vim80\spell\fr\
RD /s/q vim80\spell\ga\
RD /s/q vim80\spell\gd\
RD /s/q vim80\spell\gl\
RD /s/q vim80\spell\he\
RD /s/q vim80\spell\hr\
RD /s/q vim80\spell\hu\
RD /s/q vim80\spell\id\
RD /s/q vim80\spell\it\
RD /s/q vim80\spell\ku\
RD /s/q vim80\spell\la\
RD /s/q vim80\spell\lt\
RD /s/q vim80\spell\lv\
RD /s/q vim80\spell\mg\
RD /s/q vim80\spell\mi\
RD /s/q vim80\spell\ms\
RD /s/q vim80\spell\nb\
RD /s/q vim80\spell\nl\
RD /s/q vim80\spell\nn\
RD /s/q vim80\spell\ny\
RD /s/q vim80\spell\pl\
RD /s/q vim80\spell\pt\
RD /s/q vim80\spell\ro\
RD /s/q vim80\spell\ru\
RD /s/q vim80\spell\rw\
RD /s/q vim80\spell\sk\
RD /s/q vim80\spell\sl\
RD /s/q vim80\spell\sv\
RD /s/q vim80\spell\tet\
RD /s/q vim80\spell\sw\
RD /s/q vim80\spell\th\
RD /s/q vim80\spell\tl\
RD /s/q vim80\spell\tn\
RD /s/q vim80\spell\uk\
RD /s/q vim80\spell\yi\
RD /s/q vim80\spell\zu\
